<?php

return [
    'company' => [
        'name' => 'Heavenly Dreams',
        'contact_name' => 'Gissell Arenas',
        'office_address' => [
            'Av. Tlahuac 3632 Int. A301',
            'Col. Culhuacan',
            'Iztapalapa',
            'Ciudad de Mexico',
        ],
        'description' => [
            'Telecomunicaciones',
            'Marketing Directo',
            'Reclutamiento y Desarrollo de Talento',
            'Capacitacion Comercial',
        ],
        'mission' => 'Brindar oportunidades reales de crecimiento profesional y economico para personas comprometidas y con ganas de superarse.',
    ],
    'system_variables' => [
        'nombre',
        'edad',
        'telefono',
        'vacante',
        'experiencia',
        'ciudad',
        'fecha_entrevista',
        'hora_entrevista',
        'reclutador',
        'estatus',
    ],
    'vacancies' => [
        [
            'slug' => 'volantero',
            'name' => 'Volantero',
            'weekly_salary' => 2000,
            'age_min' => 17,
            'age_max' => 40,
            'activities' => [
                'Entrega de publicidad',
                'Promocion de servicios',
                'Apoyo en eventos',
                'Captacion de prospectos',
            ],
            'requirements' => [
                'Secundaria terminada',
                'Actitud positiva',
                'Facilidad para caminar y trabajar en campo',
            ],
            'benefits' => [],
        ],
        [
            'slug' => 'ayudante-general',
            'name' => 'Ayudante General',
            'weekly_salary' => 2300,
            'age_min' => 18,
            'age_max' => 40,
            'activities' => [
                'Apoyo operativo',
                'Organizacion de materiales',
                'Logistica interna',
                'Actividades administrativas basicas',
            ],
            'requirements' => [
                'Responsable',
                'Puntual',
                'Disponibilidad de horario',
            ],
            'benefits' => [],
        ],
        [
            'slug' => 'asesor-comercial',
            'name' => 'Asesor Comercial',
            'weekly_salary' => 2300,
            'age_min' => 18,
            'age_max' => 40,
            'activities' => [
                'Promocion de servicios',
                'Atencion a clientes',
                'Prospeccion',
                'Seguimiento de ventas',
            ],
            'requirements' => [
                'Facilidad de palabra',
                'Gusto por las ventas',
                'Actitud de servicio',
            ],
            'benefits' => [
                'Capacitacion pagada',
                'Bonos semanales',
                'Crecimiento interno',
                'Desarrollo profesional',
            ],
        ],
        [
            'slug' => 'supervisor',
            'name' => 'Supervisor',
            'weekly_salary' => 2600,
            'age_min' => 18,
            'age_max' => 40,
            'activities' => [
                'Supervision de equipos',
                'Seguimiento de indicadores',
                'Capacitacion',
                'Apoyo operativo',
            ],
            'requirements' => [
                'Liderazgo',
                'Experiencia deseable',
                'Manejo de personal',
                'Disponibilidad de horario',
            ],
            'benefits' => [
                'Bonos por productividad',
            ],
        ],
    ],
    'interview_slots' => [
        '09:30 AM',
        '09:40 AM',
        '09:50 AM',
        '10:00 AM',
        '10:10 AM',
        '10:20 AM',
        '10:30 AM',
        '10:40 AM',
        '10:50 AM',
        '11:00 AM',
    ],
    'crm_tags' => [
        'NUEVO_LEAD',
        'CONTACTADO',
        'INTERESADO',
        'FILTRADO',
        'CALIFICADO',
        'ENTREVISTA_AGENDADA',
        'CONFIRMADO',
        'REAGENDAR',
        'NO_ASISTIO',
        'EN_CAPACITACION',
        'CONTRATADO',
        'RECHAZADO',
    ],
    'faq' => [
        [
            'question' => 'La capacitacion es pagada?',
            'answer' => 'Si.',
        ],
        [
            'question' => 'Hay crecimiento?',
            'answer' => 'Si. Contamos con planes de desarrollo interno: Asesor -> Supervisor -> Gerente.',
        ],
        [
            'question' => 'Necesito experiencia?',
            'answer' => 'No necesariamente. Depende de la vacante.',
        ],
        [
            'question' => 'Donde estan ubicados?',
            'answer' => 'Av. Tlahuac 3632 Int. A301, Col. Culhuacan, Iztapalapa, CDMX.',
        ],
    ],
    'stages' => [
        [
            'key' => 'saludo_inicial',
            'title' => 'Saludo inicial',
            'summary' => 'Presentacion de Gissell Arenas y seleccion de vacante.',
        ],
        [
            'key' => 'informacion_vacante',
            'title' => 'Informacion de vacante',
            'summary' => 'Detalle de sueldo, actividades, beneficios y requisitos.',
        ],
        [
            'key' => 'filtro_automatico',
            'title' => 'Filtro automatico',
            'summary' => 'Edad, ciudad, experiencia y disponibilidad inmediata.',
        ],
        [
            'key' => 'calificacion',
            'title' => 'Calificacion',
            'summary' => 'Compatibilidad del perfil con la vacante.',
        ],
        [
            'key' => 'agendamiento',
            'title' => 'Agendamiento',
            'summary' => 'Seleccion de horario y confirmacion de entrevista.',
        ],
        [
            'key' => 'seguimiento',
            'title' => 'Seguimiento',
            'summary' => 'Recordatorios, reagenda, no show y contratacion.',
        ],
    ],
    'messages' => [
        'initial_greeting' => "Hola, muy buen dia. Mi nombre es Gissell Arenas y formo parte del area de Recursos Humanos de Heavenly Dreams. Estoy aqui para ayudarte durante todo tu proceso de seleccion. Actualmente contamos con varias vacantes disponibles en Ciudad de Mexico. En cual te gustaria recibir informacion?",
        'company_about' => "Somos una empresa mexicana especializada en telecomunicaciones, marketing directo, reclutamiento y desarrollo de talento, y capacitacion comercial. Nuestra mision es brindar oportunidades reales de crecimiento profesional y economico.",
        'qualification_success' => "Excelente {{nombre}}. Tu perfil es compatible con nuestra vacante de {{vacante}}. El siguiente paso es programar una entrevista presencial.",
        'interview_confirmation' => "Entrevista agendada para {{nombre}} en la vacante {{vacante}} el {{fecha_entrevista}} a las {{hora_entrevista}} en Av. Tlahuac 3632 Int. A301, Col. Culhuacan, Iztapalapa, Ciudad de Mexico.",
        'reminder_24h' => "Hola {{nombre}}. Te recordamos que manana tienes entrevista en Heavenly Dreams el {{fecha_entrevista}} a las {{hora_entrevista}}.",
        'reminder_2h' => "Hola {{nombre}}. Tu entrevista es en aproximadamente 2 horas. Sigues disponible para asistir?",
        'no_show' => "Hola {{nombre}}. Notamos que no pudiste asistir a tu entrevista programada. Te gustaria reagendar una nueva fecha?",
        'hired' => "Felicidades {{nombre}}. Has sido seleccionado para formar parte de Heavenly Dreams. Proximos pasos: entrega de documentos, capacitacion, integracion al equipo e inicio de actividades.",
    ],
    'vacancy_playbooks' => [
        'volantero' => [
            [
                'key' => 'field_followup',
                'trigger_stage' => 'contactado',
                'delay_hours' => 6,
                'message' => "Hola {{nombre}}, la vacante de {{vacante}} sigue abierta. Es una posicion activa en campo con ingreso semanal y arranque rapido. Si te interesa, hoy mismo podemos revisar horarios para entrevista.",
            ],
            [
                'key' => 'ready_to_schedule',
                'trigger_stage' => 'calificado',
                'delay_hours' => 18,
                'message' => "Hola {{nombre}}, tu perfil ya luce compatible para {{vacante}}. Si sigues disponible, te comparto horarios para entrevista: {{horarios_disponibles}}.",
            ],
        ],
        'ayudante-general' => [
            [
                'key' => 'ops_followup',
                'trigger_stage' => 'contactado',
                'delay_hours' => 6,
                'message' => "Hola {{nombre}}, te escribo para continuar con la vacante de {{vacante}}. Buscamos personas responsables y con disponibilidad. Si sigues interesado, avanzamos al filtro final.",
            ],
            [
                'key' => 'ops_schedule',
                'trigger_stage' => 'calificado',
                'delay_hours' => 18,
                'message' => "Hola {{nombre}}, ya podemos pasar a entrevista para {{vacante}}. Tengo horarios disponibles: {{horarios_disponibles}}.",
            ],
        ],
        'asesor-comercial' => [
            [
                'key' => 'sales_benefits',
                'trigger_stage' => 'contactado',
                'delay_hours' => 4,
                'message' => "Hola {{nombre}}, la vacante de {{vacante}} incluye capacitacion pagada, bonos y crecimiento interno. Si te interesa desarrollarte en ventas, hoy puedo ayudarte a avanzar.",
            ],
            [
                'key' => 'sales_closure',
                'trigger_stage' => 'calificado',
                'delay_hours' => 12,
                'message' => "Hola {{nombre}}, tu perfil va bien para {{vacante}}. El siguiente paso es entrevista presencial. Te puedo ofrecer estos horarios: {{horarios_disponibles}}.",
            ],
        ],
        'supervisor' => [
            [
                'key' => 'leadership_followup',
                'trigger_stage' => 'contactado',
                'delay_hours' => 6,
                'message' => "Hola {{nombre}}, retomando tu proceso para {{vacante}}. Buscamos liderazgo, seguimiento de indicadores y manejo de personal. Si sigues disponible, podemos avanzar hoy.",
            ],
            [
                'key' => 'leadership_schedule',
                'trigger_stage' => 'calificado',
                'delay_hours' => 12,
                'message' => "Hola {{nombre}}, tu perfil es fuerte para {{vacante}}. Te propongo entrevista para revisar experiencia y objetivos. Horarios disponibles: {{horarios_disponibles}}.",
            ],
        ],
    ],
    'funnel' => [
        ['key' => 'leads_recibidos', 'label' => 'Leads Recibidos'],
        ['key' => 'contactados', 'label' => 'Contactados'],
        ['key' => 'interesados', 'label' => 'Interesados'],
        ['key' => 'calificados', 'label' => 'Calificados'],
        ['key' => 'entrevistas', 'label' => 'Entrevistas'],
        ['key' => 'asistieron', 'label' => 'Asistieron'],
        ['key' => 'capacitacion', 'label' => 'Capacitacion'],
        ['key' => 'contratados', 'label' => 'Contratados'],
        ['key' => 'activos', 'label' => 'Activos'],
    ],
];
