FROM node:20-alpine AS frontend-build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci --ignore-scripts
COPY frontend/ .
ARG VITE_API_URL
ARG VITE_API_SECRET
ENV VITE_API_URL=${VITE_API_URL}
ENV VITE_API_SECRET=${VITE_API_SECRET}
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=frontend-build /app/dist /var/www/hdreams-frontend
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
